services:
  - type: web
    runtime: static
    name: pyxis-code
    repo: https://github.com/Stasshe/Pyxis-CodeCanvas
    buildCommand: pnpm run build
    staticPublishPath: out
    envVars:
      - key: NEXT_PUBLIC_IS_DEV_SERVER
        value: "true"
    previews:
      generation: automatic
